var exports = module.exports = {};

exports.PortsAndPortbytes={
        'A1':['A1'],
        'A2':['A2'],
        'A3':['A3'],
        'A4':['A4'],
        'A5':['A5'],
        'A6':['A6'],
		'mp3':['mp3'],
        'dot_matrix': ['dot_matrix1', 'dot_matrix2', 'dot_matrix3', 'dot_matrix4', 'dot_matrix5'],
        'BC':['B1','B2','B3','B4','C1','C2','C3','C4'],
        'B': ['B1','B2','B3','B4'],
        'C': ['C1','C2','C3','C4'],
        'DE':['D1','D2','D3','D4','E1','E2','E3','E4'],
        'FG':['F1','F2','F3','F4','G1','G2','G3','G4'],
        'F': ['F1','F2','F3','F4'],
        'G': ['G1','G2','G3','G4'],
        'MOTOR1':['MOTOR1'],
        'MOTOR2':['MOTOR2'],
        'Beeper':['Beeper'],
        'bid1':['Bidata1'],
        'bid2':['Bidata2'],
        'bid3':['Bidata3'],
        'bif1':['Biflag1'],
        'bif2':['Biflag2'],
        'bif3':['Biflag3'],
        'bic1':['Bicounter1 - assign'],
        'bic2':['Bicounter2 - assign'],
        'bic3':['Bicounter3 - assign'],
        'Countbic1':['Bicounter1 - '],
        'Countbic2':['Bicounter2 - '],
        'Countbic3':['Bicounter3 - '],
        'btr':['Btremote'],
        'bpr':['Beeper']
      };
      
exports.CorrespondingPortCode={
        'led' : 'P',
        'laser' : 'P',
        'beeper' : 'O',
        'geared_motor' : 'P',
        'mini_geared_motor' : 'P',
        'servo_motor' : 'S',
        'dc_motor' : 'P',
        '7segment_display' : 'O',
        '4_CH_relay':'O',
        'relay' : 'O',
        'electromagnet' : 'P',
        'mp3':'M',
        'led_strip' : 'O',
        'dot_matrix' : 'D',
        'light_sensor' : 'A',
        'bend_sensor' : 'A',
        'gas_sensor' : 'A',
        'distance_sensor' : 'A',
        'sound_sensor' : 'A',
        'temperature_sensor' : 'A',
        'rain_sensor' : 'A',
        'humidity_sensor': 'A',
        'hall_sensor' : 'A',
        'metal_detector' : 'I',
        'ultrasonic_sensor' : 'U',
        'heartbeat_sensor' : 'I',
        'rfid' : 'R',
        'joystick':'A',
        'color_sensor' : 'C',
        'tact_switch' : 'I',
        'dual_swicth':'I',
        'touch_sensor':'I',
        'pir_sensor':'I',
        'gesture_sensor':'G',
        'rotational_sensor' : 'A',
        'accelerometer' : 'A',
        'solar_panel' : 'A',
        'battery' : 'O',
        'gyro_sensor':'G',
        'compass':'P'
      };

exports.PortByteValuesIf={
        'bid1':'Bidata1',
        'bid2':'Bidata2',
        'bid3':'Bidata3',
        'bif1':'Biflag1',
        'bif2':'Biflag2',
        'bif3':'Biflag3',
        'bic1':'Bicounter1',
        'bic2':'Bicounter2',
        'bic3':'Bicounter3',
        'remote':'Btremote',
        'slider':'Btslider'
      };

exports.PortByteNumericalValuesIf={
        'A1':'1',
        'A2':'2',
        'A3':'3',
        'A4':'4',
        'A5':'5',
        'A6':'6',
        'B1':'7',
        'B2':'8',
        'B3':'9',
        'B4':'A',
        'C1':'11',
        'C2':'12',
        'C3':'13',
        'C4':'14',
        'D1':'15',
        'D2':'16',
        'D3':'17',
        'D4':'18',
        'E1':'19',
        'E2':'20',
        'E3':'21',
        'E4':'22',
        'F':'45',
        'F1':'23',
        'F2':'24',
        'F3':'25',
        'F4':'26',
        'G':'46',
        'G1':'27',
        'G2':'28',
        'G3':'29',
        'G4':'30',
        'Bicounter1':'31',
        'Bicounter2':'32',
        'Bicounter3':'33',
        'reserved for future':'34',
        'Biflag1':'35',
        'Biflag2':'36',
        'Biflag3':'37',
        'Btremote':'38',
        'Btslider': '39',
        'Bidata1':'42',  
        'Bidata2':'43',  
        'Bidata3':'44',
        'U1': '45',
        'U2': '46',       
        '_R': '47',
        '_G': '48',
        '_B': '49',
        'rfid': '50',
        'timeElapsed': '51',
        'battery': '52',
        'time': '63'
      };

exports.PortByteNumericalValuesOutput={
        'A1':'1',
        'A2':'2',
        'A3':'3',
        'A4':'4',
        'A5':'5',
        'A6':'6',
        'B1':'7',
        'B2':'8',
        'B3':'9',
        'B4':'10',
        'C1':'11',
        'C2':'12',
        'C3':'13',
        'C4':'14',
        'D1':'15',
        'D2':'16',
        'D3':'17',
        'D4':'18',
        'E1':'19',
        'E2':'20',
        'E3':'21',
        'E4':'22',
        'F1':'23',
        'F2':'24',
        'F3':'25',
        'F4':'26',
        'G1':'27',
        'G2':'28',
        'G3':'29',
        'G4':'30',
        'MOTOR1':'31',
        'MOTOR2':'32',
        'Beeper':'33',
        'reserved for future':'34',
        'Bicounter1 - increment':'35',
        'Bicounter2 - increment':'36',
        'Bicounter3 - increment':'37',
        'Bicounter1 - decrement':'38',
        'Bicounter2 - decrement':'39',
        'Bicounter3 - decrement':'40',
        'Bicounter1 - assign':'50',
        'Bicounter2 - assign':'51',
        'Bicounter3 - assign':'52',
        'Biflag1':'53',
        'Biflag2':'54',
        'Biflag3':'55',
        'Bidata1':'56',  
        'Bidata2':'57',  
        'Bidata3':'58',  
        'reserved':'59',
        'dot_matrix1':'60',
        'dot_matrix2':'61',
        'dot_matrix3':'62',
        'dot_matrix4':'63',
        'dot_matrix5':'64',
        'Btremote':'75',
        'IRdata':'76',
        "mp3":'78'
      };

exports.BiDataValuesOutput={
        'A1':'1',
        'A2':'2',
        'A3':'3',
        'A4':'4',
        'A5':'5',
        'A6':'6',
        'B1':'7',
        'B2':'8',
        'B3':'9',
        'B4':'10',
        'C1':'11',
        'C2':'12',
        'C3':'13',
        'C4':'14',
        'D1':'15',
        'D2':'16',
        'D3':'17',
        'D4':'18',
        'E1':'19',
        'E2':'20',
        'E3':'21',
        'E4':'22',
        'F1':'23',
        'F2':'24',
        'F3':'25',
        'F4':'26',
        'G1':'27',
        'G2':'28',
        'G3':'29',
        'G4':'30',
        'MOTOR1':'31',
        'MOTOR2':'32',
        'Beeper':'33',
        'reserved for future':'34',
        'bic1':'37',
        'bic2':'38',
        'bic3':'39',
        'bif1':'40',
        'bif2':'41',
        'bif3':'42',
        'bid1':'43',  
        'bid2':'44',  
        'bid3':'45',  
        'reserved':'59',
        'btr':'46',
        'bts':'47'
      };

exports.nodeDefaultCodes={
        "wait":"w",
        "if":"d",
        "else":"d",
        "endif":"0ED",
        "endelse":"0ED",
        "loop":"l00",
        "endloop":"0EL",
        "output":"o{",
        "repeat":"RST",
        "end":"END"
      };