
      module.exports = {
      "PA":{
            "dual_splitter":function(port){return{"min":0,"max":255}},
      },
      "PC":{
             "dual_splitter":function(port){return{"min":0,"max":255}},
       },
      "A1": {"led" : function(port){ return {"min": 0, "max": 1}},
             "laser" : function(port){ return {"min": 0, "max": 1}}, 
             "beeper" : function(port){ return {"min": 0, "max": 1}}, 
             "light_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "bend_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "gas_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "distance_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "sound_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "temperature_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rain_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rotational_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "accelerometer" : function(port){ return {"min": 0, "max": 1024}},
             "solar_panel" : function(port){ return {"min": 0, "max": 1024}},
             "humidity_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "hall_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "metal_detector" : function(port){ return {"min": 0, "max": 1}},
             "heartbeat_sensor" : function(port){ return {"min": 0, "max": 1}},
             "tact_switch" : function(port){ return {"min": 0, "max": 1}},
             "dual_switch" : function(port){ return {"min": 0, "max": 1}},
             "touch_sensor":function(port){ return {"min": 0, "max": 1}},
             "pir_sensor":function(port){ return {"min": 0, "max": 1}}
      },
      "A2": {"led" : function(port){ return {"min": 0, "max": 65535}},
             "laser" : function(port){ return {"min": 0, "max": 65535}},
             "beeper" : function(port){ return {"min": 0, "max": 1}},
             "servo_extender" : function(port){ return {"min": 0, "max": 1}},
             "servo_motor" : function(port){ return {"min": 0, "max": 180}},
             "light_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "bend_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "gas_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "distance_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "sound_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "temperature_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rain_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rotational_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "accelerometer" : function(port){ return {"min": 0, "max": 1024}},
             "solar_panel" : function(port){ return {"min": 0, "max": 1024}},
             "humidity_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "hall_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "metal_detector" : function(port){ return {"min": 0, "max": 1}},
             "heartbeat_sensor" : function(port){ return {"min": 0, "max": 1}},
             "tact_switch" : function(port){ return {"min": 0, "max": 1}},
             "dual_switch" : function(port){ return {"min": 0, "max": 1}},
             "touch_sensor":function(port){ return {"min": 0, "max": 1}},
             "pir_sensor":function(port){ return {"min": 0, "max": 1}}
      },
      "A3": {"led" : function(port){ return {"min": 0, "max": 65535}},
             "laser" : function(port){ return {"min": 0, "max": 65535}},
             "beeper" : function(port){ return {"min": 0, "max": 1}},
             "servo_motor" : function(port){ return {"min": 0, "max": 180}},
             "servo_extender" : function(port){ return {"min": 0, "max": 1}},
             "light_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "bend_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "gas_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "distance_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "sound_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "temperature_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rain_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rotational_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "accelerometer" : function(port){ return {"min": 0, "max": 1024}},
             "solar_panel" : function(port){ return {"min": 0, "max": 1024}},
             "humidity_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "hall_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "metal_detector" : function(port){ return {"min": 0, "max": 1}},
             "heartbeat_sensor" : function(port){ return {"min": 0, "max": 1}},
             "tact_switch" : function(port){ return {"min": 0, "max": 1}},
             "dual_switch" : function(port){ return {"min": 0, "max": 1}},
             "touch_sensor":function(port){ return {"min": 0, "max": 1}},
             "pir_sensor":function(port){ return {"min": 0, "max": 1}}
      },
      "A4": {"led" : function(port){ return {"min": 0, "max": 1}},
             "laser" : function(port){ return {"min": 0, "max": 1}},
             "beeper" : function(port){ return {"min": 0, "max": 1}},
             "light_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "bend_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "gas_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "distance_sensor" : function(port){ return {"min": 0, "max": 1024}}, 
             "sound_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "temperature_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rain_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "rotational_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "accelerometer" : function(port){ return {"min": 0, "max": 1024}},
             "solar_panel" : function(port){ return {"min": 0, "max": 1024}},
             "humidity_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "hall_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "metal_detector" : function(port){ return {"min": 0, "max": 1}},
             "heartbeat_sensor" : function(port){ return {"min": 0, "max": 1}},
             "tact_switch" : function(port){ return {"min": 0, "max": 1}},
             "dual_switch" : function(port){ return {"min": 0, "max": 1}},
             "touch_sensor":function(port){ return {"min": 0, "max": 1}},
             "pir_sensor":function(port){ return {"min": 0, "max": 1}}
      },
      "BC": {
             "7segment_display" : function(port){ return {"min": 0, "max": 1}},
             "led_strip" : function(port){ return {"min": 0, "max": 1}},
             "accelerometer" : function(port){ return {"min": 0, "max": 1024}},
             "rfid" : function(port){ return {"min": 0, "max": 65535}},
             "dot_matrix" : function(port){ return {"min": 0, "max": 5}},
             "4_ch_relay" : function(port){ return {"min": 0, "max": 1}},

      },
      "B": {
             "accelerometer" : function(port){ return {"min": 0, "max": 1024}},
             "rfid" : function(port){ return {"min": 0, "max": 65535}},
             "dot_matrix" : function(port){ return {"min": 0, "max": 5}},
             'octa_splitter':function(port){return{"min":0,"max":1}},

      },
      "F": {
             "ultrasonic_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "color_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "mp3":function(port){return{"min":0,"max":255}},
             "dual_splitter":function(port){return{"min":0,"max":255}},

      },
      "G": {
             "ultrasonic_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "color_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "dual_splitter":function(port){return{"min":0,"max":255}},
             "gesture_sensor":function(port){ return {"min": 0, "max": 1024}},
             "gyro_sensor":function(port){ return {"min": 0, "max": 1024}},
             "compass":function(port){return{"min":0,"max":360}},
             "accelerometer" : function(port){ return {"min": -1024, "max": 1024}},
      },
      "FG": {
             "accelerometer" : function(port){ return {"min": 0, "max": 1024}},
             "ultrasonic_sensor" : function(port){ return {"min": 0, "max": 1024}},
             "color_sensor" : function(port){ return {"min": 0, "max": 1024}},


      },
      "MOTOR1": {
             "geared_motor" : function(port){return {"min": -20, "max": 20}},
             "mini_geared_motor" : function(port){return {"min": -20, "max": 20}},
             "dc_motor" : function(port){return {"min": -20, "max": 20}},
             "relay" : function(port){return {"min": -20, "max": 20}},
             "electromagnet" : function(port){return {"min": -20, "max": 20}},
      },
      "MOTOR2": {
             "geared_motor" : function(port){return {"min": -20, "max": 20}},
             "mini_geared_motor" : function(port){return {"min": -20, "max": 20}},
             "dc_motor" : function(port){return {"min": -20, "max": 20}},
             "relay" : function(port){return {"min": -20, "max": 20}},
             "electromagnet" : function(port){return {"min": -20, "max": 20}},
      },
      "F1":{
            "led" : function(port){ return {"min": 0, "max": 1}},
            "laser" : function(port){ return {"min": 0, "max": 1}},
            "beeper" : function(port){ return {"min": 0, "max": 1}},
            "tact_switch" : function(port){ return {"min": 0, "max": 1}},
      },
      "F2":{
            "led" : function(port){ return {"min": 0, "max": 1}},
            "laser" : function(port){ return {"min": 0, "max": 1}},
            "beeper" : function(port){ return {"min": 0, "max": 1}},
            "tact_switch" : function(port){ return {"min": 0, "max": 1}}, 
      },
      "G1":{
            "led" : function(port){ return {"min": 0, "max": 1}},
            "laser" : function(port){ return {"min": 0, "max": 1}},
            "beeper" : function(port){ return {"min": 0, "max": 1}},
            "tact_switch" : function(port){ return {"min": 0, "max": 1}},
      },
      "G2":{
            "led" : function(port){ return {"min": 0, "max": 1}},
            "laser" : function(port){ return {"min": 0, "max": 1}},
            "beeper" : function(port){ return {"min": 0, "max": 1}},
            "tact_switch" : function(port){ return {"min": 0, "max": 1}}, 
      },
  



};
