
module.exports = {
      "A1": {"led" : function(logic){ return 'WRITE_LOGIC(A1,'+logic['A1']+');'},
             "laser" : function(logic){ return 'WRITE_LOGIC(A1,'+logic['A1']+');'}, 
             "light_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "bend_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "gas_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "distance_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "sound_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "temperature_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "rain_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "humidity_sensor" : function(port){ return 'READ_ADC(A1);'},
             "hall_sensor" : function(port){ return 'READ_ADC(A1);'},
             "metal_detector" : function(port){ return 'READ_ADC(A1);'},
             "heartbeat_sensor" : function(port){ return 'READ_ADC(A1);'},
             "rotational_sensor" : function(port){ return 'READ_ADC(A1);'}, 
             "accelerometer" : function(port){ return 'READ_ADC(A1);'},
             "tact_switch" : function(port){ return 'READ_ADC(A1);'},
             "dual_switch":function(port){ return 'READ_ADC(A1);'},
             "solar_panel" : function(port){ return 'READ_ADC(A1);'},
             "touch_sensor":function(port){return 'READ_ADC(A1);'},
             "pir_sensor":function(port){return 'READ_ADC(A1);'}
      },
      "A2": {"led" : function(logic){ return 'WRITE_PWM(A2,'+logic['A2']+');'},
             "laser" : function(logic){ return 'WRITE_LOGIC(A2,'+logic['A2']+');'},
             "servo_motor" : function(degree){ return 'SERVO(A2,'+degree['A2']+');'},
             "light_sensor" : function(port){ return 'READ_ADC(A2);'},
             "bend_sensor" : function(port){ return 'READ_ADC(A2);'},
             "gas_sensor" : function(port){ return 'READ_ADC(A2);'},
             "distance_sensor" : function(port){ return 'READ_ADC(A2);'},
             "sound_sensor" : function(port){ return 'READ_ADC(A2);'},
             "temperature_sensor" : function(port){ return 'READ_ADC(A2);'},
             "rain_sensor" : function(port){ return 'READ_ADC(A2);'},
             "humidity_sensor" : function(port){ return 'READ_ADC(A2);'},
             "hall_sensor" : function(port){ return 'READ_ADC(A2);'},
             "metal_detector" : function(port){ return 'READ_ADC(A2);'},
             "heartbeat_sensor" : function(port){ return 'READ_ADC(A2);'},
             "rotational_sensor" : function(port){ return 'READ_ADC(A2);'},
             "accelerometer" : function(port){ return 'READ_ADC(A2);'},
             "tact_switch" : function(port){ return 'READ_ADC(A2);'},
             "dual_switch":function(port){ return 'READ_ADC(A2);'},
             "solar_panel" : function(port){ return 'READ_ADC(A2);'},
             "touch_sensor":function(port){return 'READ_ADC(A2);'},
             "pir_sensor":function(port){return 'READ_ADC(A2);'}
      },
      "A3": {"led" : function(logic){ return 'WRITE_PWM(A3,'+logic['A3']+');'},
             "laser" : function(logic){ return 'WRITE_LOGIC(A3,'+logic['A3']+');'},
             "servo_motor" : function(degree){ return 'SERVO(A3,'+degree['A3']+');'},
             "light_sensor" : function(port){ return 'READ_ADC(A3);'},
             "bend_sensor" : function(port){ return 'READ_ADC(A3);'},
             "gas_sensor" : function(port){ return 'READ_ADC(A3);'},
             "distance_sensor" : function(port){ return 'READ_ADC(A3);'},
             "sound_sensor" : function(port){ return 'READ_ADC(A3);'},
             "temperature_sensor" : function(port){ return 'READ_ADC(A3);'},
             "rain_sensor" : function(port){ return 'READ_ADC(A3);'},
             "humidity_sensor" : function(port){ return 'READ_ADC(A3);'},
             "hall_sensor" : function(port){ return 'READ_ADC(A3);'},
             "metal_detector" : function(port){ return 'READ_ADC(A3);'},
             "heartbeat_sensor" : function(port){ return 'READ_ADC(A3);'},
             "rotational_sensor" : function(port){ return 'READ_ADC(A3);'},
             "accelerometer" : function(port){ return 'READ_ADC(A3);'},
             "tact_switch" : function(port){ return 'READ_ADC(A3);'},
             "dual_switch":function(port){ return 'READ_ADC(A3);'},
             "solar_panel" : function(port){ return 'READ_ADC(A3);'},
             "touch_sensor":function(port){return 'READ_ADC(A3);'},
             "pir_sensor":function(port){return 'READ_ADC(A3);'}
      },
      "A4": {"led" : function(logic){ return 'WRITE_LOGIC(A4,'+logic['A4']+');'},
             "laser" : function(logic){ return 'WRITE_LOGIC(A4,'+logic['A4']+');'},
             "light_sensor" : function(port){ return 'READ_ADC(A4);'},
             "bend_sensor" : function(port){ return 'READ_ADC(A4);'},
             "gas_sensor" : function(port){ return 'READ_ADC(A4);'},
             "distance_sensor" : function(port){ return 'READ_ADC(A4);'},
             "sound_sensor" : function(port){ return 'READ_ADC(A4);'},
             "temperature_sensor" : function(port){ return 'READ_ADC(A4);'},
             "rain_sensor" : function(port){ return 'READ_ADC(A4);'},
             "humidity_sensor" : function(port){ return 'READ_ADC(A4);'},
             "hall_sensor" : function(port){ return 'READ_ADC(A4);'},
             "metal_detector" : function(port){ return 'READ_ADC(A4);'},
             "heartbeat_sensor" : function(port){ return 'READ_ADC(A4);'},
             "rotational_sensor" : function(port){ return 'READ_ADC(A4);'},
             "accelerometer" : function(port){ return 'READ_ADC(A4);'},
             "tact_switch" : function(port){ return 'READ_ADC(A4);'},
             "dual_switch":function(port){ return 'READ_ADC(A4);'},
             "solar_panel" : function(port){ return 'READ_ADC(A4);'},
             "touch_sensor":function(port){return 'READ_ADC(A4);'},
             "pir_sensor":function(port){return 'READ_ADC(A4);'}
      },
      "BC": {
             "7segment_display" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
             "4_CH_relay" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
             "led_strip" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
             "accelerometer" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
             "dot_matrix" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
             "rfid" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
      },
      "B": {
             "accelerometer" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
             "dot_matrix" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
             "rfid" : function(ports){ return 'WRITE_LOGIC(B1,'+(ports['b1']||'LOW')+');WRITE_LOGIC(B2,'+(ports['b2']||'LOW')+');WRITE_LOGIC(B3,'+(ports['b3']||'LOW')+');WRITE_LOGIC(B4,'+(ports['b4']||'LOW')+');WRITE_LOGIC(C1,'+(ports['c1']||'LOW')+');WRITE_LOGIC(C2,'+(ports['c2']||'LOW')+');WRITE_LOGIC(C3,'+(ports['c3']||'LOW')+');WRITE_LOGIC(C4,'+(ports['c4']||'LOW')+');'},
      },      
      "DE": {"led" : function(port){ return 'SET_AS_OUT('+port+');'},
             "geared_motor" : function(port){ return 'SET_AS_OUT('+port+');'},
             "servo_motor" : function(port){ return 'SET_AS_OUT('+port+');'},
             "dc_motor" : function(port){ return 'SET_AS_OUT('+port+');'},
             "accelerometer" : function(port){ return 'SET_AS_IN('+port+');'},
      },
      "FG": {
             "ultrasonic_sensor" : function(port){ return 'ULTRASONIC_READ('+port+');'},
             "color_sensor" : function(port){ return 'COLOR_SENSOR_READ('+port+');'},
             "mp3":function(port){ return 'COLOR_SENSOR_READ('+port+');'},
             "gesture_sensor":function(port){ return 'COLOR_SENSOR_READ('+port+');'}
      },
      "MOTOR1": {
             "geared_motor" : function(speed){ var direction;if(speed['MOTOR1']){if(speed['MOTOR1']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR1('+direction+','+speed['MOTOR1']+');'},
             "dc_motor" : function(speed){ var direction;if(speed['MOTOR1']){if(speed['MOTOR1']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR1('+direction+','+speed['MOTOR1']+');'},
             "relay" : function(speed){ var direction;if(speed['MOTOR1']){if(speed['MOTOR1']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR1('+direction+','+speed['MOTOR1']+');'},
             "electromagnet" : function(speed){ var direction;if(speed['MOTOR1']){if(speed['MOTOR1']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR1('+direction+','+speed['MOTOR1']+');'}
      },
      "MOTOR2": {
             "geared_motor" : function(speed){ var direction;if(speed['MOTOR2']){if(speed['MOTOR2']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR2('+direction+','+speed['MOTOR2']+');'},
             "dc_motor" : function(speed){ var direction;if(speed['MOTOR2']){if(speed['MOTOR2']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR2('+direction+','+speed['MOTOR2']+');'},
             "electromagnet" : function(speed){ var direction;if(speed['MOTOR2']){if(speed['MOTOR2']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR2('+direction+','+speed['MOTOR2']+');'},
             "relay" : function(speed){ var direction;if(speed['MOTOR2']){if(speed['MOTOR2']<0){direction="ANTICLOCKWISE"}else{direction="CLOCKWISE"}} return 'MOTOR2('+direction+','+speed['MOTOR2']+');'}
      },
      "G1":{
            "led" : function(logic){ return 'WRITE_LOGIC(G1,'+logic['G1']+');'},
            "laser" : function(logic){ return 'WRITE_LOGIC(G1,'+logic['G1']+');'}, 
            "dual_switch":function(port){ return 'READ_ADC(G1);'},
      },
      "G2":{
             "led" : function(logic){ return 'WRITE_LOGIC(G2,'+logic['G2']+');'},
            "laser" : function(logic){ return 'WRITE_LOGIC(G2,'+logic['G2']+');'}, 
            "dual_switch":function(port){ return 'READ_ADC(G2);'},
      },
      "F1":{
             "led" : function(logic){ return 'WRITE_LOGIC(F1,'+logic['F1']+');'},
            "laser" : function(logic){ return 'WRITE_LOGIC(F1,'+logic['F1']+');'}, 
            "dual_switch":function(port){ return 'READ_ADC(F1);'},
      },
      "F2":{
             "led" : function(logic){ return 'WRITE_LOGIC(F2,'+logic['F2']+');'},
            "laser" : function(logic){ return 'WRITE_LOGIC(F2,'+logic['F2']+');'}, 
            "dual_switch":function(port){ return 'READ_ADC(F2);'},
      },


};
