module.exports = {
      "led" : function(port){ return 'SET_AS_OUT('+port+');'},
      "laser" : function(port){ return 'SET_AS_OUT('+port+');'},
      "beeper" : function(port){ return 'SET_AS_OUT('+port+');'},
      "geared_motor" : function(port){ return 'SET_AS_OUT('+port+');'},
      "mini_geared_motor" : function(port){ return 'SET_AS_OUT('+port+');'},
      "servo_motor" : function(port){ return 'SET_AS_OUT('+port+');'},
      "dc_motor" : function(port){ return 'SET_AS_OUT('+port+');'},
      "dot_matrix" : function(port){ return 'SET_AS_OUT('+port+');'},
      "mp3" : function(port){ return 'SET_AS_OUT('+port+');'},
      "dual_splitter" : function(port){ return 'SET_AS_OUT('+port+');'},
      "octa_splitter" : function(port){ return 'SET_AS_OUT('+port+');'},
      "7segment_display" : function(port){ return 'SET_AS_OUT('+port+');'},
      "4_CH_relay" : function(port){ return 'SET_AS_OUT('+port+');'},
      "electromagnet" : function(port){ return 'SET_AS_OUT('+port+');'},
      "relay" : function(port){ return 'SET_AS_OUT('+port+');'},
      "led_strip" : function(port){ return 'SET_AS_OUT('+port+');'},
      "light_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "bend_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "gas_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "distance_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "sound_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "humidity_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "hall_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "metal_detector" : function(port){ return 'SET_AS_IN('+port+');'},
      "ultrasonic_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "heartbeat_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "rfid" : function(port){ return 'SET_AS_IN('+port+');'},
      "temperature_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "rain_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "rotational_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "accelerometer" : function(port){ return 'SET_AS_IN('+port+');'},
      "solar_panel" : function(port){ return 'SET_AS_IN('+port+');'},
      "colour_sensor" : function(port){ return 'SET_AS_IN('+port+');'},
      "tact_switch" : function(port){ return 'SET_AS_IN('+port+');'},
      "dual_switch":function(port){ return 'SET_AS_IN('+port+');'}, 
      "gyro_sensor":function(port){ return 'SET_AS_IN('+port+');'}, 

};